version: "3.8"

services:
  ####################################
  # mysql database  
  ####################################
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order

  ##################################
  # Pytest on Games Service
  ##################################
  games-pytest:
    build:
      context: ../
      dockerfile: ci/Dockerfile.test
    depends_on:
      - mysql
    environment:
      db_conn: mysql+mysqlconnector://root:root@mysql:3306
